export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SEND_NOTIFICATION_MODEL = 'SEND_NOTIFICATION_MODEL';
export const SHOW_NOTIFICATION_MODEL = 'SHOW_NOTIFICATION_MODEL';
export const SHOW_INVITATION_MODEL = 'SHOW_INVITATION_MODEL';
export const CANCEL_SEND_REQUEST = 'CANCEL_SEND_REQUEST';
export const ACCEPT_SENT_REQUEST = 'ACCEPT_SENT_REQUEST';
export const GENERATE_SECURITY_CODE = 'GENERATE_SECURITY_CODE';
export const SHOW_GENERATING_CODE_MODEL = 'SHOW_GENERATING_CODE_MODEL';
export const SHOW_CONFIRMATION_CODE_MODEL = 'SHOW_CONFIRMATION_CODE_MODEL';
export const REQUEST_SUCCEED = 'REQUEST_SUCCEED';

