export const GET_MY_DATA = 'GET_MY_DATA';
export const CHECK_MY_NOTIFICATION = 'CHECK_MY_NOTIFICATION';
export const GET_MY_ACCEPTED_REQUEST = 'GET_MY_ACCEPTED_REQUEST';
export const GET_MY_CONFIRMATION_REQUEST = 'GET_MY_CONFIRMATION_REQUEST';
export const UPLOADING_IMAGE_FAILD = 'UPLOADING_IMAGE_FAILD';
export const UPLOADING_IMAGE = 'UPLOADING_IMAGE';
export const USER_DATA = 'USER_DATA';
